---
#update hooks command:
#poetry run pre-commit autoupdate
exclude: '\.ya?ml$'

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    - id: check-yaml
    - id: check-json
    - id: check-ast
    - id: check-toml
    - id: check-docstring-first
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: check-added-large-files
      args: ["--maxkb=500"]
    - id: trailing-whitespace
    - id: fix-byte-order-marker
    - id: mixed-line-ending
    - id: requirements-txt-fixer
    - id: end-of-file-fixer
    - id: detect-private-key
    - id: debug-statements
    - id: name-tests-test
-   repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
        args: [--max-line-length=240, '--ignore=F401']
# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: v1.7.0
#     hooks:
#     -   id: mypy
#         additional_dependencies: [types-all]
#         exclude: ^(rms/|dte/|utils/)
-   repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
    -   id: black
        exclude: fixtures
-   repo: https://github.com/python-poetry/poetry
    rev: '1.7.1'  
    hooks:
    -   id: poetry-check
